[package]
name = "evm-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
rsp-client-executor = {git = "https://github.com/succinctlabs/rsp.git"}
bincode = "1.3.3"
serde_json = "1.0.133"
nmt-rs = {git="https://github.com/Sovereign-Labs/nmt-rs.git"}